### ISSUE TITLE
Prune very large polygons

### ISSUE THREAD

**Issue by matthewhanson** [stactools-packages/sentinel2#113]
Getting some generated Items with unusually large polygons.  

As an example here is a tileInfo with a large tileDataGeometry (over 3000 points):

[https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/37/W/EP/2019/3/16/0/tileInfo.json](https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/37/W/EP/2019/3/16/0/tileInfo.json)

But it is actually not a complex looking polygon:
<img width="617" alt="image" src="https://github.com/stactools-packages/sentinel2/assets/1416900/1cb3d991-18b1-49da-a821-52a55a0e8988">

Here are some additional examples:
[https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/7/V/EF/2019/3/16/0/tileInfo.json](https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/7/V/EF/2019/3/16/0/tileInfo.json)

[https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/27/W/VP/2019/3/26/0/tileInfo.json](https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/27/W/VP/2019/3/26/0/tileInfo.json)

[https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/27/W/VP/2019/3/16/0/tileInfo.json](https:///roda.sentinel-hub.com/sentinel-s2-l2a/tiles/27/W/VP/2019/3/16/0/tileInfo.json)

**Comment by matthewhanson** [comment]
There are currently 59291 scenes affected by this problem, currently the largest source of failures when running against the entire archive.

**Comment by gadomski** [comment]
There's a `tolerance` argument that can be used to simplify the output geometry: https://github.com/stactools-packages/sentinel2/blob/e38be03164cee8f1111e93ea4711943d799e74fb/src/stactools/sentinel2/stac.py#L100

In local testing, I was able to get down to a simple five point geometry via `--tolerance` on the command line:

```shell
$ stac sentinel2 create-item . . --tolerance 0.01 2>/dev/null
$ jq .geometry.coordinates S2B_OPER_MSI_L2A_TL_SGS__20190316T131240_A010572_T37WEP.json 
[
  [
    [
      40.539615644930294,
      65.72605561889523
    ],
    [
      41.39255666409265,
      65.71506827539704
    ],
    [
      41.487571441091816,
      66.69921264081667
    ],
    [
      41.41469787851801,
      66.69998805472711
    ],
    [
      40.539615644930294,
      65.72605561889523
    ]
  ]
]
```

![Screenshot 2023-08-22 at 11 42 42 AM](https://github.com/stactools-packages/sentinel2/assets/58314/7b400314-594a-4691-b0bd-1861a2d195f5)

So I _think_ this issue is invalid, already done, but @matthewhanson can you confirm?

**Comment by philvarner** [comment]
https://github.com/stactools-packages/sentinel2/pull/129
